;=======================延时宏=======================================
DALAY MACRO
LOCAL W1
	MOV CX,0FFFFH
	PUSH AX
W1:
	IN	AL,61H
	AND AL,00010000B
	CMP AL,AH
	JE W1
	MOV AH,AL
	LOOP W1
	POP AX
ENDM

;=================================画目标宏========================
GOALL MACRO
	MOV GOCXL,256
	MOV GODXL,140
	CALL GOAL
	
	MOV GOCXL,296
	MOV GODXL,140
	CALL GOAL

	MOV GOCXL,336
	MOV GODXL,140
	CALL GOAL
	
ENDM

;================================完成度判断=========================
GO_JUDGE MACRO
	MOV COUNT,3
	MOV CX,FI_GOCX
	SUB CX,14
	MOV DX,FI_GODX
	J_COLOR CX,DX
	CMP AL,0EH
	JNE NEXT1
	MOV BL,COUNT
	DEC BL
	MOV COUNT,BL
NEXT1:
	MOV CX,SE_GOCX
	SUB CX,14
	MOV DX,SE_GODX
	J_COLOR CX,DX
	CMP AL,0EH
	JNE NEXT2
	MOV BL,COUNT
	DEC BL
	MOV COUNT,BL
NEXT2:
	MOV CX,TH_GOCX
	SUB CX,14
	MOV DX,TH_GODX
	J_COLOR CX,DX
	CMP AL,0EH
	JNE NEXT3
	MOV BL,COUNT
	DEC BL
	MOV COUNT,BL
NEXT3:
ENDM
;==============================画空白块宏====================================

KONG MACRO	
	BLANKFUN 240,120;280,160
	BLANKFUN 280,120;320,160
	BLANKFUN 320,120;360,160
	
	BLANKFUN 280,160;320,200
	BLANKFUN 320,160;360,200
	
	BLANKFUN 280,200;320,240
	BLANKFUN 320,200;360,240
	
	BLANKFUN 240,240;280,280
	BLANKFUN 280,240;320,280
	BLANKFUN 320,240;360,280
	BLANKFUN 360,240;400,280
	
	BLANKFUN 240,280;280,320
	BLANKFUN 280,280;320,320
	BLANKFUN 320,280;360,320
	
	BLANKFUN 240,320;280,360
	BLANKFUN 280,320;320,360
ENDM


;============================画箱子宏========================================

BOXFUN MACRO BOXX1,BOXY1,U_COLOR
	MOV XZCX1,BOXX1
	MOV XZDX1,BOXY1
	;MOV XZCX2,BOXX2
	;MOV XZDX2,BOXY2
	MOV UNI_COLOR,U_COLOR
	CALL BOX
ENDM


;=============================箱子模块重绘宏=======================================

BOXBLOCK MACRO
	MOV CX,FI_XZCX1
	MOV DX,FI_XZDX1
	MOV BL,FI_U_COLOR
	BOXFUN CX,DX,BL
	
	MOV CX,SE_XZCX1
	MOV DX,SE_XZDX1
	MOV BL,SE_U_COLOR
	BOXFUN CX,DX,BL
	
	MOV CX,TH_XZCX1
	MOV DX,TH_XZDX1
	MOV BL,TH_U_COLOR
	BOXFUN CX,DX,BL

ENDM
;==========================空白块宏===================================

BLANKFUN MACRO BKX1,BKY1;BKX2,BKY2
	MOV BLCX1,BKX1
	MOV BLDX1,BKY1
	;MOV BLCX2,BKX2
	;MOV BLDX2,BKY2
	CALL BLANK
ENDM
;===========================人物宏======================================

MANFUN MACRO MANX1,MANY1,MANX2,MANY2
LOCAL STEP_INC
	MOV MANCX1,MANX1
	MOV MANDX1,MANY1
	MOV MANCX2,MANX2
	MOV MANDX2,MANY2
	CALL MAN
	
	MOV AH,02H
    MOV BH,0
    MOV DX,0423H
    INT 10H
    
	MOV DL,STEP
	INC DL
	CMP DL,3AH
	JC STEP_INC
	MOV STEP,30H
	MOV DL,STEPT
	INC DL
	MOV STEPT,DL
STEP_INC:
	MOV STEP,DL

	MOV DL,STEPT
	MOV AH,02
	INT 21H
	
	MOV DL,STEP
	MOV AH,02
	INT 21H
	
ENDM

;===========================键盘输入等待宏====================================

PRESS MACRO
	MOV AH,00
	INT 16H
	JUDGE
ENDM

;=============================按键判断宏========================================

JUDGE MACRO	
LOCAL WWWW,LAST
	CMP AL,77H
	JE WWWW
	CMP AL,61H
	JE AAAA
	CMP AL,73H
	JE SSSS
	CMP AL,64H
	JE DDDD
	JMP LAST
DDDD:
	D_PRESS
	JMP LAST
SSSS:
	S_PRESS
	JMP LAST
AAAA:
	A_PRESS
	JMP LAST
WWWW:
	W_PRESS
LAST:
ENDM

;============================按w键的处理宏===========================================
W_PRESS MACRO
LOCAL BOUNDW,W_FIBOX,W_SEBOX,W_THBOX,W_MAN
	MOV CX,MANCX1
	ADD CX,20
	MOV DX,MANDX1
	SUB DX,20
	J_COLOR CX,DX
	MOV TEMCOLOR,AL
	CMP TEMCOLOR,09H
	JE W_MAN
	CMP TEMCOLOR,02H
	JE W_FIBOX
	CMP TEMCOLOR,03H
	JE W_SEBOX
	CMP TEMCOLOR,06H
	JE W_THBOX
	JMP BOUNDW
W_THBOX:
	MOV CX,TH_XZCX1
	MOV DX,TH_XZDX1
	W_P_BOX
	CMP DX,TH_XZDX1
	JE BOUNDW
	MOV TH_XZDX1,DX
	JMP W_MAN
W_SEBOX:
	MOV CX,SE_XZCX1
	MOV DX,SE_XZDX1
	W_P_BOX
	CMP DX,SE_XZDX1
	JE BOUNDW
	MOV SE_XZDX1,DX
	JMP W_MAN
W_FIBOX:
	MOV CX,FI_XZCX1
	MOV DX,FI_XZDX1
	W_P_BOX
	CMP DX,FI_XZDX1
	JE BOUNDW
	MOV FI_XZDX1,DX
	JMP W_MAN
W_MAN:
	MOV CX,MANCX1
	MOV BLCX1,CX 
	MOV DX,MANDX1
	MOV BLDX1,DX
	SUB MANDX1,40
	SUB MANDX2,40
	CALL BLANK
	BOXBLOCK
	CALL MAN
BOUNDW:
ENDM
;=================w键后对箱子的处理宏==
W_P_BOX MACRO 
LOCAL W_P_BEND
	ADD CX,10
	SUB DX,10
	J_COLOR CX,DX
	SUB CX,10
	ADD DX,10
	CMP AL,09H
	JNE W_P_BEND
	SUB DX,40
W_P_BEND:
ENDM

;============================按A键的处理宏===========================================
A_PRESS MACRO
LOCAL BOUNDA,A_FIBOX,A_SEBOX,A_THBOX,A_MAN
	MOV CX,MANCX1
	SUB CX,20
	MOV DX,MANDX1
	ADD DX,20
	J_COLOR CX,DX
	MOV TEMCOLOR,AL
	CMP TEMCOLOR,09H
	JE A_MAN
	CMP TEMCOLOR,02H
	JE A_FIBOX
	CMP TEMCOLOR,03H
	JE A_SEBOX
	CMP TEMCOLOR,06H
	JE A_THBOX
	JMP BOUNDA
A_THBOX:
	MOV CX,TH_XZCX1
	MOV DX,TH_XZDX1
	A_P_BOX
	CMP CX,TH_XZCX1
	JE BOUNDA
	MOV TH_XZCX1,CX
	JMP A_MAN
A_SEBOX:
	MOV CX,SE_XZCX1
	MOV DX,SE_XZDX1
	A_P_BOX
	CMP CX,SE_XZCX1
	JE BOUNDA
	MOV SE_XZCX1,CX
	JMP A_MAN
A_FIBOX:
	MOV CX,FI_XZCX1
	MOV DX,FI_XZDX1
	A_P_BOX
	CMP CX,FI_XZCX1
	JE BOUNDA
	MOV FI_XZCX1,CX
	JMP A_MAN
A_MAN:
	MOV DX,MANDX1
	MOV BLDX1,DX
	MOV CX,MANCX1
	MOV BLCX1,CX 
	SUB MANCX1,40
	SUB MANCX2,40
	CALL BLANK
	BOXBLOCK
	CALL MAN
BOUNDA:
ENDM


;=================A键后对箱子的处理宏==
A_P_BOX MACRO
LOCAL A_P_BEND
	SUB CX,10
	ADD DX,10
	J_COLOR CX,DX
	ADD CX,10
	SUB DX,10
	CMP AL,09H
	JNE A_P_BEND
	SUB CX,40
A_P_BEND:
ENDM



;============================按S键的处理宏===========================================
S_PRESS MACRO
LOCAL BOUNDS
	MOV CX,MANCX2
	SUB CX,20
	MOV DX,MANDX2
	ADD DX,20
	J_COLOR CX,DX
	MOV TEMCOLOR,AL
	CMP TEMCOLOR,09H
	JE S_MAN
	CMP TEMCOLOR,02H
	JE S_FIBOX
	CMP TEMCOLOR,03H
	JE S_SEBOX
	CMP TEMCOLOR,06H
	JE S_THBOX
	JMP BOUNDS
S_THBOX:
	MOV CX,TH_XZCX1
	MOV DX,TH_XZDX1
	S_P_BOX
	CMP DX,TH_XZDX1
	JE BOUNDS
	MOV TH_XZDX1,DX
	JMP S_MAN
S_SEBOX:
	MOV CX,SE_XZCX1
	MOV DX,SE_XZDX1
	S_P_BOX
	CMP DX,SE_XZDX1
	JE BOUNDS
	MOV SE_XZDX1,DX
	JMP S_MAN
S_FIBOX:
	MOV CX,FI_XZCX1
	MOV DX,FI_XZDX1
	S_P_BOX
	CMP DX,FI_XZDX1
	JE BOUNDS
	MOV FI_XZDX1,DX
	JMP S_MAN
S_MAN:
	MOV CX,MANCX1
	MOV BLCX1,CX
	MOV DX,MANDX1
	MOV BLDX1,DX
	ADD MANDX1,40
	ADD MANDX2,40
	CALL BLANK
	BOXBLOCK
	CALL MAN
BOUNDS:
ENDM

S_P_BOX MACRO
LOCAL S_P_BEND
	ADD CX,10
	ADD DX,50
	J_COLOR CX,DX
	SUB CX,10
	SUB DX,50
	CMP AL,09H
	JNE S_P_BEND
	ADD DX,40
S_P_BEND:
ENDM


;============================按D键的处理宏===========================================
D_PRESS MACRO
LOCAL BOUNDD,D_MAN
	MOV CX,MANCX2
	ADD CX,20
	MOV DX,MANDX2
	SUB DX,20
	J_COLOR CX,DX
	MOV TEMCOLOR,AL
	CMP TEMCOLOR,09H
	JE D_MAN
	CMP TEMCOLOR,02H
	JE D_FIBOX
	CMP TEMCOLOR,03H
	JE D_SEBOX
	CMP TEMCOLOR,06H
	JE D_THBOX
	JMP BOUNDD
D_THBOX:
	MOV CX,TH_XZCX1
	MOV DX,TH_XZDX1
	D_P_BOX
	CMP CX,TH_XZCX1
	JE BOUNDD
	MOV TH_XZCX1,CX
	JMP D_MAN
D_SEBOX:
	MOV CX,SE_XZCX1
	MOV DX,SE_XZDX1
	D_P_BOX
	CMP CX,SE_XZCX1
	JE BOUNDD
	MOV SE_XZCX1,CX
	JMP D_MAN
D_FIBOX:
	MOV CX,FI_XZCX1
	MOV DX,FI_XZDX1
	D_P_BOX
	CMP CX,FI_XZCX1
	JE BOUNDD
	MOV FI_XZCX1,CX
	JMP D_MAN
D_MAN:
	MOV DX,MANDX1
	MOV BLDX1,DX
	MOV CX,MANCX1
	MOV BLCX1,CX
	ADD MANCX1,40
	ADD MANCX2,40
	CALL BLANK
	BOXBLOCK
	CALL MAN
BOUNDD:
ENDM

D_P_BOX MACRO
LOCAL D_P_BEND
	ADD CX,50
	ADD DX,10
	J_COLOR CX,DX
	SUB CX,50
	SUB DX,10
	CMP AL,09H
	JNE D_P_BEND
	ADD CX,40
D_P_BEND:
ENDM

;================================取颜色宏============================================

J_COLOR MACRO COLOR_CX,COLOR_DX
	MOV AH,0DH
	MOV CX,COLOR_CX
	MOV DX,COLOR_DX
	INT 10H
ENDM

;=================================================================

PUBLIC XZCX1,XZDX1	;	箱子坐标区间
PUBLIC BLCX1,BLDX1	;	空白块坐标区间
PUBLIC MANCX1,MANDX1,MANCX2,MANDX2		; 	人坐标区间
PUBLIC GOCXL,GODXL
PUBLIC UNI_COLOR

PUBLIC COUNT
	EXTRN BOX:NEAR
	EXTRN BG:NEAR
	EXTRN BLANK:NEAR
	EXTRN MAN:NEAR
	EXTRN GOAL:NEAR
	.MODEL SMALL
	.STACK	
	.DATA
	

;===========================公用变量===========================

STEPH DB 30H
STEPT DB 30H
STEP DB 30H
YOUWIN DB 'Good job! You win!','$'
UNI_COLOR DB ?	
XZCX1 DW ?
XZDX1 DW ?
;XZCX2 DW ?
;XZDX2 DW ?

BLCX1 DW ?
BLDX1 DW ?
;BLCX2 DW ?
;BLDX2 DW ?

MANCX1 DW ?
MANDX1 DW ?
MANCX2 DW ?
MANDX2 DW ?

GOCXL DW ?
GODXL DW ?

;=============================针对箱子的信息记录变量==============================
	;第一个箱子信息
	COUNT DB ?
	FI_U_COLOR DB ?	
	FI_XZCX1 DW ?
	FI_XZDX1 DW ?
	
	;第二个箱子信息
	SE_U_COLOR DB ?	
	SE_XZCX1 DW ?
	SE_XZDX1 DW ?
	
	;第三个箱子信息
	TH_U_COLOR DB ?	
	TH_XZCX1 DW ?
	TH_XZDX1 DW ?
	;
	TEMCOLOR DB ?
;==============================针对目标的信息记录变量==================================
	FI_GOCX DW ?
	FI_GODX DW ?
	SE_GOCX DW ?
	SE_GODX DW ?
	TH_GOCX DW ?
	TH_GODX DW ?
;===================================================================================
	.CODE
	
	
MAIN:
	MOV AX,@DATA
	MOV DS,AX
	
;==================模式选择===================================== 
    MOV AX,0012H
    INT 10H
;====================背景色=====================================  
    MOV AH,0BH
    MOV BH,0
	MOV BL,07H
	INT 10H
	
;==========================大背景砖头绘制==========================
	CALL BG
;===========================空白块===================================
	KONG
;============================目标描绘======================================
	GOALL
;===========================箱子=======================================
	;箱子1
	MOV CX,280
	MOV DX,160
	MOV BL,02H
	MOV FI_XZCX1,CX
	MOV FI_XZDX1,DX
	MOV FI_U_COLOR,BL
	BOXFUN CX,DX,BL
	
	;箱子2
	MOV CX,280
	MOV DX,240
	MOV BL,03H
	MOV SE_XZCX1,CX
	MOV SE_XZDX1,DX
	MOV SE_U_COLOR,BL
	BOXFUN CX,DX,BL
	
	;箱子3
	MOV CX,320
	MOV DX,240
	MOV BL,06H
	MOV TH_XZCX1,CX
	MOV TH_XZDX1,DX
	MOV TH_U_COLOR,BL
	BOXFUN CX,DX,BL

	
	;BOXFUN 280,240,03H
	;BOXFUN 320,240,06H

;=============================人物块======================================

	MANFUN 280,200,320,240
	
	MOV FI_GOCX,256
	MOV FI_GODX,140
	MOV SE_GOCX,296
	MOV SE_GODX,140
	MOV TH_GOCX,336
	MOV TH_GODX,140
	
;======================人物控制==========================================

AGAINA:
	PRESS
	GOALL
	GO_JUDGE
	CMP COUNT,0
	JE WIN
	JMP AGAINA	
WIN:	
	MOV AH,00H
	MOV AL,03H
	INT 10H
	
	MOV AH,02
	MOV BH,00
	MOV DX,0919H
	INT 10H
	
	MOV AH,09H
	MOV DX,OFFSET YOUWIN
	INT 21H
	
	
	MOV AH,4CH
	INT 21H
	
END MAIN


















